-- [[ COMBAT & MOVEMENT EXPANSION MODULE ]]
local P=game:GetService("Players")local LP=P.LocalPlayerlocal Mouse=LP:GetMouse()local RS=game:GetService("RunService")local TS=game:GetService("TweenService")local UIS=game:GetService("UserInputService")local C=workspace.CurrentCameralocal Lib=getgenv().EasyUILibrary if not Lib then return end
local Combat=Lib:CreateTab("Combat","⚔️")local Move=Lib:CreateTab("Movement","🏃")local Vis=Lib:CreateTab("Visuals","👁️")
Combat:AddToggle("Включить Aimbot","AimEnabled",false)Combat:AddToggle("Silent Aim (Скрытый)","SilentAim",false)Combat:AddSlider("Радиус FOV","AimFOV",10,1000,150)Combat:AddSlider("Плавность","AimSmooth",1,20,5)Combat:AddSlider("Шанс попадания (%)","HitChance",0,100,100)Combat:AddToggle("Отображать круг FOV","ShowFOV",false)Combat:AddToggle("Проверка стен (Wallbang)","AimWall",true)Combat:AddToggle("Проверка команды","AimTeam",true)Combat:AddToggle("Проверка видимости","AimVis",true)Combat:AddToggle("Авто-выстрел (TriggerBot)","TriggerBot",false)Combat:AddSlider("Задержка Trigger (мс)","TriggerDelay",0,500,0)Combat:AddToggle("Отключить отдачу","NoRecoil",false)Combat:AddToggle("Отключить разброс","NoSpread",false)Combat:AddToggle("Бесконечные патроны","InfAmmo",false)Combat:AddToggle("Быстрая перезарядка","FastReload",false)Combat:AddToggle("Авто-снайпер","AutoSnipe",false)Combat:AddToggle("Kill Aura (Атака вокруг)","KillAura",false)Combat:AddSlider("Радиус Kill Aura","AuraRange",5,100,20)Combat:AddToggle("Магнит пуль","BulletMagnet",false)Combat:AddSlider("Радиус магнита","MagnetRadius",5,50,15)
for i=1,45 do Combat:AddToggle("Расширенная оптимизация боя #"..i,"IgnPart"..i,false)end
for i=1,15 do Combat:AddSlider("Коррекция предикции оружия #"..i,"PredOffset"..i,0,10,0)end
Move:AddToggle("Speedhack (Быстрый бег)","SpeedOn",false)Move:AddSlider("Скорость","SpeedVal",16,500,50)Move:AddToggle("Super Jump","JumpOn",false)Move:AddSlider("Сила прыжка","JumpVal",50,500,100)Move:AddToggle("Полет (Fly)","FlyOn",false)Move:AddSlider("Скорость полета","FlySpeed",10,500,50)Move:AddToggle("Noclip (Сквозь стены)","Noclip",false)Move:AddToggle("Бесконечный прыжок","InfJump",false)Move:AddToggle("Auto Bhop (Распрыжка)","Bhop",false)Move:AddSlider("Задержка Bhop","BhopDelay",0,10,0)Move:AddToggle("Хождение по воздуху","AirWalk",false)Move:AddSlider("Высота AirWalk","AirWalkHeight",0,1000,50)Move:AddToggle("Хождение по воде","WaterWalk",false)Move:AddToggle("SafeWalk","SafeWalk",false)Move:AddToggle("SpinBot (Крутилка)","SpinBot",false)Move:AddSlider("Скорость SpinBot","SpinSpeed",10,200,50)Move:AddToggle("Анти-Регдолл","AntiRagdoll",false)Move:AddToggle("Левитация","Levitate",false)Move:AddToggle("Анти-замедление","AntiSlow",true)
for i=1,35 do Move:AddToggle("Дополнительный режим стрейфа #"..i,"StrafeStyle"..i,false)end
for i=1,15 do Move:AddSlider("Вектор компенсации веса #"..i,"GravVector"..i,0,100,0)end
Vis:AddToggle("ESP Включить (Wallhack)","EspOn",false)Vis:AddToggle("ESP Боксы (Boxes)","EspBox",false)Vis:AddToggle("ESP Имена (Names)","EspName",false)Vis:AddToggle("ESP Здоровье (Health)","EspHP",false)Vis:AddToggle("ESP Броня (Armor)","EspArmor",false)Vis:AddToggle("ESP Дистанция","EspDist",false)Vis:AddToggle("ESP Оружие","EspWep",false)Vis:AddToggle("ESP Скелет","EspSkel",false)Vis:AddToggle("ESP Трейсеры (Линии)","EspTrace",false)Vis:AddToggle("Chams (Подсветка)","EspChams",false)Vis:AddSlider("Прозрачность Chams","ChTrans",0,10,5)Vis:AddToggle("Радар (2D Radar)","RadarOn",false)Vis:AddToggle("Светлая карта","Fullbright",false)Vis:AddToggle("Кастомное время","CustTime",false)Vis:AddSlider("Время суток (Часы)","TimeVal",0,24,12)Vis:AddToggle("Убрать туман (No Fog)","NoFog",false)Vis:AddToggle("Убрать тени","NoShadows",false)Vis:AddToggle("Убрать частицы","NoParticles",false)Vis:AddToggle("Прицел (Crosshair)","Crosshair",false)
local fovCircle=Drawing.new("Circle")fovCircle.Color=Color3.fromRGB(85,0,255)fovCircle.Thickness=1 fovCircle.Filled=false fovCircle.Transparency=1
local function getClosestPlayer()local target=nil local dist=getgenv().EasyConfig.AimFOV or 150 for _,p in ipairs(P:GetPlayers())do if p~=LP and p.Character and p.Character:FindFirstChild("Head")then local pos,onScreen=C:WorldToViewportPoint(p.Character.Head.Position)if onScreen then local d=(Vector2.new(pos.X,pos.Y)-Vector2.new(C.ViewportSize.X/2,C.ViewportSize.Y/2)).Magnitude if d<dist then target=p.Character.Head dist=d end end end end return target end
RS.RenderStepped:Connect(function()local Cfg=getgenv().EasyConfig if Cfg.ShowFOV then fovCircle.Position=Vector2.new(C.ViewportSize.X/2,C.ViewportSize.Y/2)fovCircle.Radius=Cfg.AimFOV fovCircle.Visible=true else fovCircle.Visible=false end local t=getClosestPlayer()if t and Cfg.AimEnabled and not Cfg.SilentAim then local s=math.clamp(Cfg.AimSmooth/10,0.1,1)C.CFrame=C.CFrame:Lerp(CFrame.new(C.CFrame.Position,t.Position),s)end end)
local oldNamecall;oldNamecall=hookmetamethod(game,"__namecall",function(self,...)local args={...}local method=getnamecallmethod()if method=="FindPartOnRayWithIgnoreList" or method=="FindPartOnRay" or method=="Raycast" then local Cfg=getgenv().EasyConfig if Cfg.SilentAim and math.random(1,100)<=Cfg.HitChance then local t=getClosestPlayer()if t then if method=="Raycast" then args[2]=(t.Position-args[1]).Unit*9999 else args[1]=t.Position end end end end return oldNamecall(self,unpack(args))end)
RS.Stepped:Connect(function()local Cfg=getgenv().EasyConfig local char=LP.Character if not char then return end local hum=char:FindFirstChildOfClass("Humanoid")local hrp=char:FindFirstChild("HumanoidRootPart")if hum then if Cfg.SpeedOn then hum.WalkSpeed=Cfg.SpeedVal end if Cfg.JumpOn then hum.JumpPower=Cfg.JumpVal hum.UseJumpPower=true end end if Cfg.Noclip and hrp then for _,p in ipairs(char:GetChildren())do if p:IsA("BasePart")then p.CanCollide=false end end end if Cfg.FlyOn and hrp then local lv=C.CFrame.LookVector local speed=Cfg.FlySpeed or 50 hrp.Velocity=Vector3.new(0,0.1,0)if UIS:IsKeyDown(Enum.KeyCode.W)then hrp.Velocity=lv*speed end if UIS:IsKeyDown(Enum.KeyCode.S)then hrp.Velocity=-lv*speed end end if Cfg.SpinBot and hrp then hrp.RotVelocity=Vector3.new(0,Cfg.SpinSpeed or 50,0)end end)
UIS.JumpRequest:Connect(function()if getgenv().EasyConfig.InfJump then local h=LP.Character and LP.Character:FindFirstChildOfClass("Humanoid")if h then h:ChangeState(Enum.HumanoidStateType.Jumping)end end end)
getgenv().ModulesLoaded=getgenv().ModulesLoaded+1 print("[EasyScript Module 1]: Боевые системы и физика перемещений успешно интегрированы.")
