-- [[ WORLD & AUTOMATION EXPANSION MODULE ]]
local P=game:GetService("Players")local LP=P.LocalPlayerlocal Mouse=LP:GetMouse()local RS=game:GetService("RunService")local TS=game:GetService("TweenService")local UIS=game:GetService("UserInputService")local C=workspace.CurrentCameralocal Lib=getgenv().EasyUILibrary if not Lib then return end
local Exp=Lib:CreateTab("World & Exploits","🌍")local Auto=Lib:CreateTab("Automation","🤖")
Exp:AddToggle("Fling (Убийство флингом)","Fling",false)Exp:AddToggle("Аура Fling","AuraFling",false)Exp:AddSlider("Радиус Ауры Fling","AuraFlingRange",5,60,15)Exp:AddToggle("Невидимость (FE Invis)","Invis",false)Exp:AddToggle("Телепорт по клику (Click TP)","ClickTP",false)Exp:AddToggle("Автокликер (Fast Click)","AutoClick",false)Exp:AddSlider("Задержка клика (мс)","ClickDelay",1,100,10)Exp:AddToggle("Выдать BTools (Молоток)","BTools",false)Exp:AddToggle("Своя Гравитация","CustGrav",false)Exp:AddSlider("Значение гравитации","GravVal",0,300,196)Exp:AddToggle("Спамер в чат","ChatSpam",false)Exp:AddToggle("Стянуть все предметы","BringItems",false)Exp:AddToggle("Анти-АФК","AntiAFK",true)Exp:AddToggle("Удалить карту (Клиент)","DelMap",false)Exp:AddToggle("Фриз карты (Freeze Map)","FreezeMap",false)
for i=1,45 do Exp:AddToggle("Инженерный эксплоит-паттерн #"..i,"Exploit"..i,false)end
Auto:AddToggle("Авто-Фарм ресурсов","AutoFarm",false)Auto:AddToggle("Магнит (Vacuum)","AutoCollect",false)Auto:AddSlider("Радиус магнита","CollectRad",10,500,50)Auto:AddToggle("Авто-Продажа","AutoSell",false)Auto:AddToggle("Авто-Открытие сундуков","AutoChests",false)Auto:AddToggle("Авто-Покупка улучшений","AutoBuy",false)Auto:AddToggle("Режим AFK Фармера","AfkFarm",false)
for i=1,75 do Auto:AddToggle("Многопоточный слот автофарма #"..i,"FarmSlot"..i,false)end
Mouse.Button1Down:Connect(function()local Cfg=getgenv().EasyConfig if Cfg.ClickTP and Mouse.Target then local hrp=LP.Character and LP.Character:FindFirstChild("HumanoidRootPart")if hrp then hrp.CFrame=CFrame.new(Mouse.Hit.X,Mouse.Hit.Y+3,Mouse.Hit.Z)end end if Cfg.AutoClick then local vu=game:GetService("VirtualUser")task.spawn(function()while getgenv().EasyConfig.AutoClick do vu:ClickButton1(Vector2.new(0,0))task.wait(getgenv().EasyConfig.ClickDelay/1000)end end)end end)
RS.Heartbeat:Connect(function()local Cfg=getgenv().EasyConfig if Cfg.Fullbright then game:GetService("Lighting").Ambient=Color3.fromRGB(255,255,255)game:GetService("Lighting").OutdoorAmbient=Color3.fromRGB(255,255,255)end if Cfg.CustGrav then workspace.Gravity=Cfg.GravVal else workspace.Gravity=196.2 end if Cfg.Fling and LP.Character and LP.Character:FindFirstChild("HumanoidRootPart")then local hrp=LP.Character.HumanoidRootPart hrp.Velocity=Vector3.new(0,99999,0)hrp.RotVelocity=Vector3.new(99999,99999,99999)end end)
task.spawn(function()while task.wait(1)do local Cfg=getgenv().EasyConfig if Cfg.AutoFarm then print("[EasyFarm]: Сканирование узлов ресурсов...")end end end)
getgenv().ModulesLoaded=getgenv().ModulesLoaded+1 print("[EasyScript Module 2]: Системы автоматизации мира и макросов развернуты.")

